name: Build Workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    if: github.repository == 'mirkosertic/MetaIR'
    environment: ci
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: "temurin"
          cache: maven
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - run: mvn --no-transfer-progress --batch-mode --settings .mvn/settings.xml clean javadoc:jar deploy -P signed
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
      - name: Generate images from test code
        run: |
          find . -name "*.dot" -exec dot -Tsvg {} -o {}.svg \;
      - name: Generate index.html for examples directory
        run: |
          find ./target/metair-test -type d -print -exec sh -c 'tree "$0" -H "." -L 1 --noreport --houtro "" --dirsfirst --charset utf-8 -I "index.html" -T "MetaIR Examples" --ignore-case --timefmt "%d-%b-%Y %H:%M" -s -D -o "$0/index.html"' {} \;
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./target/metair-test
          CLEAN: true