name: Pull Request
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    if: github.repository == 'mirkosertic/MetaIR'
    environment: ci
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: "temurin"
          cache: maven
      - name: Install OpenCL
        run: sudo apt-get install ocl-icd-opencl-dev          
      - run: mvn --no-transfer-progress --batch-mode --settings .mvn/settings.xml clean javadoc:jar verify
